#
#     ▄▄▄▄    ██ ▄█▀▓█████▄  █    ██ ▓█████  ██▓
#    ▓█████▄  ██▄█▒ ▒██▀ ██▌ ██  ▓██▒▓█   ▀ ▓██▒
#    ▒██▒ ▄██▓███▄░ ░██   █▌▓██  ▒██░▒███   ▒██░
#    ▒██░█▀  ▓██ █▄ ░▓█▄   ▌▓▓█  ░██░▒▓█  ▄ ▒██░
#    ░▓█  ▀█▓▒██▒ █▄░▒████▓ ▒▒█████▓ ░▒████▒░██████▄
#    ░▒▓███▀▒▒ ▒░ ▒▓▒ ▒ ▒ ░░ ▒░ ░░ ▒░▓  ░ ░░ ░ ▒ ▒▒
#    ▒ ▓▒ ▒▒▓  ▒▒ ▒░ ░ ▒  ▒ ░░▒░ ░ ░  ░ ░  ░   ░ ░
#    ▒░▒   ░ ░ ░  ░ ░  ░ ░  ░  ░░░ ░ ░     ░    ░
#     ░    ░ ░ ░    ░       ░   ░    ░       ▒
#     ░      ░  ░        ░
#          ░
#
#         ® BkPlugins | discord.gg/2MHgyjCuPc
#                    Made by: Bkr__
#
# *----------------------*=/[HOW TO USE THE TEXT ANIMATOR]\=*---------------------*
#
# Currently you can only add animation to item names (the GUI buttons), and the NPC hologram. Only one animation per line is allowed.
# Item lore animations coming in the future.
#
# To animate a text, you need to provide the animation you want, and the color of the text.
# Example: "{shine red} Hello, World!"
# This will animate the entire line.
#
# You may also provide some options.
# You can make the text bold, change the speed of the animation, the amount of time
# to pause between every cycle of the animation, and the size of the animation.
# Example: "{shine red bold speed[5]} Hello, World!"
# This will make the shine animation that is bold red and updates every 5 ticks.
#
# If you don't want to animate the entire line, you need to use the text[] option
# and put only the text you want to animate inside of it.
# Example: "This is an {shine red text[animated text]}, this is not."
# The result will be "This is an animated text, this is not." but only the words "animated text" will be animated.
# ------
# The available options are:
#
# speed[<number>] | How fast does the animation update (in ticks), lowest is 1. Default is 3 if none is provided.
# pause[<number>] | The amount of time the animation will be paused after it finishes. The lower the speed, the higher this needs to be. Default is 3.
# size[<number>]  | The size of the animation, has different effects for different animations. Default is 3 if none is provided.
# text[<text>]    | The text that you want to animate. (If you don't want to animate the entire line)
# bold            | Makes the text and the animation bold.
# ------
# Available animations: (more in the future)
#
# shine | Gives a "reflective shine" effect to texts.
# ------
#
# Colors (use the color names, not the symbols):
# yellow is &e   | blue is &9      | green is &2      | red is &4      | purple is &5   |
# white is &f    | black is &0     | gray is &7       | darkblue is &1 | darkgray is &8 |
# lightred is &c | lightblue is &b | lightgreen is &a | pink is &d
# *----------------------------------*=[|]=*-------------------------------------*


# You can add any language by creating a file in the "langs" folder then setting it's name in the "language" option bellow
# Languages that come with the plugin are: en_US and pt_BR.
# Você pode adicionar qualquer idioma criando um arquivo na pasta "langs" e adicionando o seu nome na opção "language" abaixo
# Idiomas suportados por padrão: en_US e pt_BR
language: en_US

# What you need to type to cancel the inputs in the plugin.
# O que você precisa digitar para cancelar os inputs no plugin.
cancel-input: 'cancel'

# (In a future version, not implemented yet) Choose if you want the plugin to display 5 or 15 kits per page.
# (Em uma versão futura, ainda não implementado) Escolha se você quer que o plugin mostre 5 ou 15 kits por página.
expanded-kit-list: false

# Cost to start a duel. Both players need to pay it
# Custo para iniciar um X1. Os dois jogadores prrecisam pagar
duel-cost: 100

# Change to "true" if you want to allow the fighters to choose if they drop items when they die. They can't allow the drop for kits.
# Mude para "true" para permitir que os lutadores escolham se eles querem dropar itens ao morrer. Eles não podem dropar itens de kits.
player-drop-item: false

# When this is enabled, everyone in the server will get a message when a duel starts, ends, and when someone is being challenged.
# Quando esta opção está habilitada, todos no servidor receberão uma mensagem quando um X1 começa, termina, e quando alguém é desafiado.
broadcast-to-all: true

# This is how long the plugin will wait for an answer when a player is challenged
# Quanto tempo o plugin vai esperar por uma resposta a um desafio X1
challenge-expire: 30

# When this option is enabled the plugin will close the inventory of all the players when it is reloading. This is used to prevent players from taking items from menus when the plugin is disabled.
# Quando essa opção está habilitada o plugin irá fechar o inventário de todos os jogadores quando ele está dando reload. Essa opção preveni jogadores de tirarem itens do menu quando o plugin está desativado.
close-inventory-on-reload: true

# How many seconds for the duel to start after both players are ready
# Quantos segundos para iniciar o X1 depois que ambos os jogadores estiverem prontos
start-countdown: 5

# Time to wait for the winner to pick up the losers items when they die.
# Tempo para esperar o vencedor pegar os itens do perdedor quando ele morre.
time-to-pick-items: 10

# This is what shows up when a player selects a random arena or kit.
# Isso aparece quando um jogador seleciona um kit ou arena aleatória.
random-selection: '&1&kI&2&ki&3&kI&4&ki&5&kI&6&ki&e&ki&b&kI'

# The chat tag for the player with the most duel wins. Supported chat plugins: LegendChat, nChat and HeroChat
# A tag do chat do jogador com mais vitórias de X1s. Plugins de chat suportados: LegendChat, nChat e HeroChat
top-1-tag: '&6&l[Killer]&r '

# Configs for the NPC feature. You need to have Citizens and HolographicDisplays intalled for this feature to work.
# Configurações da função de NPC. Você precisa ter o Citizens e HolographicDisplays instalados para essa função funcionar.
top-1-npc:
  # Disables or enables the NPC feature. To use it type '/duel npc location' then '/duel npc update'
  # Desativa ou ativa a função NPC. Para usar digite '/x1 npc local' depois '/x1 npc atualizar'
  enabled: true

  # The text that shows up on top of the NPC
  # O text que aparece em cima do NPC
  hologram:
    # Set this to 'false' to disable the sword animation bellow the text
    # Coloque 'false' para desativar a animação da espada abaixo do texto
    sword-animation: true

    # Tags {wins} {defeats} {disconnects} {duels} {player} {kdr}
    # Placeholder support soon
    # Suporte a placeholders em breve
    lines:
      - '&7&l---=[{shine red bold text[Top Fighter]}&7&l]=---'
      - ''
      - '&7&l---=[&4&l{player}&7&l]=---'
      - '&7&l| Wins: &4&l{wins} &7&l|'
      - '&7&l| KDR: &4&l{kdr} &7&l|'
  npc:
    look-at-players:
      # Set to 'false' to disable the NPC looking at players
      # Coloque 'false' para desativar o NPC olhar para os jogadores
      enabled: true

      # The distance in blocks for the NPC to start looking at players
      # A distancia em blocos pro NPC começar a olhar pro jogador
      distance-to-look: 5
    random-look-around:
      # When there is no one near the NPC it will randomly look around. Set to 'false' to disable
      # Quando não tem jogadores perto do NPC ele fica olhando pros lados aleatoriamente. Coloque 'false' para desativar
      enabled: true
      radom-look-range:
        # How far to the LEFT the NPC will be able to turn
        # A discancia que o NPC vai poder virar para a ESQUERDA
        left-range: 70

        # How far to the RIGHT the NPC will be able to turn
        # A discancia que o NPC vai poder virar para a DIREITA
        right-range: 70

        # How far UP the NPC will be able to look
        # A distancia que o NPC vai poder olhar para CIMA
        up-range: 10

        # How far DOWN the NPC will be able to look
        # A distancia que o NPC vai poder olhar para BAIXO
        down-range: 10
    # The location of the NPC. Use the command '/duel npc location' to set it.
    # O local do NPC. Use o comando '/x1 npc local' pra setar.
    location:
      world: 'world'
      x: '0'
      y: '0'
      z: '0'
      pitch: '0'
      yaw: '0'

# (In a future version, not implemented yet) Options for the player bets.
# (Em uma versão futura, ainda não implementado) Opções para as apostas de jogadores.
player-bets:
  enabled: false
  money-bet:
    min: 1000
    max: 5000
  item-bet:
    enabled: false