name: BkDuel
version: ${project.version}
main: me.bkrmt.bkduel.BkDuel
depend:
  - 'Vault'
softdepend:
  - 'Citizens'
  - 'HeroChat'
  - 'HeroChatPro'
  - 'Legendchat'
  - 'HolographicDisplays'
  - 'nChat'
api-version: 1.13
authors: [ Bkr__ ]
description: Duel Plugin
